import os
import sys

from bs4 import BeautifulSoup
from pybaseball.datasources.bref import BRefSession

# stores the color for the line for each team.
# generated by chatgpt, very helpful!
# NOTE chatgpt had lots of color clashes. I am overriding many colors.
COLORS_CACHE = {
    'BAL': '#DF4601',  # Baltimore Orioles
    'NYY': '#003087',  # New York Yankees
    'TOR': '#0066ff',  # Toronto Blue Jays
    'TBR': '#8FBCE6',  # Tampa Bay Rays
    'BOS': '#BD3039',  # Boston Red Sox
    'DET': '#FA4616',  # Detroit Tigers
    'KCR': '#BD9B60',  # Kansas City Royals
    'CLE': '#E31937',  # Cleveland Guardians
    'CHW': '#27251F',  # Chicago White Sox
    'MIN': '#002B5C',  # Minnesota Twins
    'LAA': '#BA0021',  # Los Angeles Angels
    'ATH': '#33cc33',  # Oakland Athletics
    'SEA': '#005C5C',  # Seattle Mariners
    'HOU': '#EB6E1F',  # Houston Astros
    'TEX': '#003278',  # Texas Rangers
    'WSN': '#14225A',  # Washington Nationals
    'ATL': '#EAAA00',  # Atlanta Braves
    'NYM': '#FF5910',  # New York Mets
    'MIA': '#00A3E0',  # Miami Marlins
    'PHI': '#E81828',  # Philadelphia Phillies
    'STL': '#0C2340',  # St. Louis Cardinals
    'PIT': '#FDB827',  # Pittsburgh Pirates
    'MIL': '#B6922E',  # Milwaukee Brewers
    'CIN': '#C6011F',  # Cincinnati Reds
    'CHC': '#0E3386',  # Chicago Cubs
    'LAD': '#005A9C',  # Los Angeles Dodgers
    'SFG': '#FD5A1E',  # San Francisco Giants
    'SDP': '#2F241D',  # San Diego Padres
    'COL': '#33006F',  # Colorado Rockies
    'ARI': '#A71930'   # Arizona Diamondbacks
}

# this is a nice Session in pb that automatically spaces
# out requests to avoid bans.
session = BRefSession()

def get_soup(url: str) -> BeautifulSoup:
    s = session.get(url).content # type: ignore
    return BeautifulSoup(s, "lxml")

# the two functions below are nice for blocking print statements
# from pybaseball
def block_print():
    sys.stdout = open(os.devnull, 'w', encoding='utf-8')

def enable_print():
    sys.stdout = sys.__stdout__
